# Generated by Django 3.1.8 on 2021-08-10 07:04

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('sport', '0074_reference_comment_uploaded'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='student',
            managers=[
                ('objects_with_hours', django.db.models.manager.Manager()),
            ],
        ),
    ]
