# Generated by Django 3.1.8 on 2021-12-16 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sport', '0096_attendance_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='training',
            name='deleted',
            field=models.DateTimeField(editable=False, null=True),
        ),
    ]
